// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO6ypqtdhcSJdsL9v9opFblfR9EothczM',
    appId: '1:993656855338:web:fddb2c454437ef05ed5c53',
    messagingSenderId: '993656855338',
    projectId: 'pushnotitutorial-eaf02',
    authDomain: 'pushnotitutorial-eaf02.firebaseapp.com',
    storageBucket: 'pushnotitutorial-eaf02.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqM8nZhmM2z4Bcy9rbzfpHc4UsFzZvpxw',
    appId: '1:993656855338:android:8ba9c1235f5c264bed5c53',
    messagingSenderId: '993656855338',
    projectId: 'pushnotitutorial-eaf02',
    storageBucket: 'pushnotitutorial-eaf02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUNNNRUv7QXYkMhDxbWBA-iSRE8k39mwA',
    appId: '1:993656855338:ios:5cb472d17bba4681ed5c53',
    messagingSenderId: '993656855338',
    projectId: 'pushnotitutorial-eaf02',
    storageBucket: 'pushnotitutorial-eaf02.appspot.com',
    iosBundleId: 'com.example.pushnotitutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUNNNRUv7QXYkMhDxbWBA-iSRE8k39mwA',
    appId: '1:993656855338:ios:ad56d17d30ddd3b5ed5c53',
    messagingSenderId: '993656855338',
    projectId: 'pushnotitutorial-eaf02',
    storageBucket: 'pushnotitutorial-eaf02.appspot.com',
    iosBundleId: 'com.example.pushnotitutorial.RunnerTests',
  );
}
